import type { Space } from "@/lib/types";

export const mockSpaces: Space[] = [
  {
    id: "space-001",
    title: "Quiet Loft - Roma Norte",
    type: "studio",
    area: "Roma Norte",
    distanceKm: 0.8,
    pricePer30m: 14,
    instantAccess: true,
    imageUrl: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=600&q=80",
    rating: 4.8,
    reviewCount: 124,
    description: "Loft moderno y discreto en el corazon de Roma Norte. Ambiente intimo con iluminacion ambiental, cama king size y bano privado. Acceso con codigo digital.",
    amenities: ["Wi-Fi", "Aire acondicionado", "Cama King", "Bano privado", "Cerradura digital", "Toallas"],
    reviews: [
      { id: "r1", alias: "Usuario A.", rating: 5, comment: "Increible lugar, muy limpio y discreto. Acceso super rapido.", date: "2026-03-15" },
      { id: "r2", alias: "Pareja M.", rating: 5, comment: "Perfecto para una escapada rapida. La ubicacion es ideal.", date: "2026-03-10" },
      { id: "r3", alias: "Usuario K.", rating: 4, comment: "Muy bueno, el aire acondicionado funciona perfecto. Solo faltaron amenidades extra.", date: "2026-03-05" },
    ],
  },
  {
    id: "space-002",
    title: "Private Room - Condesa",
    type: "private-room",
    area: "Condesa",
    distanceKm: 1.4,
    pricePer30m: 12,
    instantAccess: true,
    imageUrl: "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=600&q=80",
    rating: 4.6,
    reviewCount: 89,
    description: "Habitacion privada en zona tranquila de la Condesa. Decoracion minimalista, muy limpia y con todo lo necesario para un momento de privacidad.",
    amenities: ["Wi-Fi", "Aire acondicionado", "Cama Queen", "Bano privado", "Cerradura digital"],
    reviews: [
      { id: "r4", alias: "Usuario R.", rating: 5, comment: "La mejor relacion precio-calidad. Muy comodo y privado.", date: "2026-03-18" },
      { id: "r5", alias: "Pareja J.", rating: 4, comment: "Buen lugar, tranquilo. El acceso fue inmediato.", date: "2026-03-12" },
      { id: "r6", alias: "Usuario F.", rating: 5, comment: "Repeat visitor. Siempre limpio y disponible. 10/10.", date: "2026-03-01" },
    ],
  },
  {
    id: "space-003",
    title: "1BR Apartment - Juarez",
    type: "apartment-1br",
    area: "Juarez",
    distanceKm: 2.2,
    pricePer30m: 18,
    instantAccess: true,
    imageUrl: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600&q=80",
    rating: 4.9,
    reviewCount: 203,
    description: "Apartamento completo de 1 recamara con sala, cocina y bano. Ideal para quienes buscan mas espacio y comodidad. Terraza privada con vista.",
    amenities: ["Wi-Fi", "Aire acondicionado", "Cama King", "Cocina", "Terraza", "Smart TV", "Cerradura digital", "Toallas"],
    reviews: [
      { id: "r7", alias: "Pareja L.", rating: 5, comment: "El mejor espacio que hemos reservado. La terraza es un plus increible.", date: "2026-03-20" },
      { id: "r8", alias: "Usuario D.", rating: 5, comment: "Wow. Parece un Airbnb premium pero por 30 minutos. Genial concepto.", date: "2026-03-16" },
      { id: "r9", alias: "Usuario S.", rating: 4, comment: "Excelente departamento, muy amplio. Un poco lejos pero vale la pena.", date: "2026-03-08" },
    ],
  },
  {
    id: "space-004",
    title: "Suite Romantica - Polanco",
    type: "private-room",
    area: "Polanco",
    distanceKm: 3.1,
    pricePer30m: 22,
    instantAccess: true,
    imageUrl: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80",
    rating: 4.9,
    reviewCount: 156,
    description: "Suite de lujo con jacuzzi privado e iluminacion ambiental. Decoracion romantica, sabanas de algodon egipcio y amenidades premium.",
    amenities: ["Jacuzzi", "Iluminacion ambiental", "Cama King", "Sabanas premium", "Bano de lujo", "Cerradura digital", "Champagne disponible"],
    reviews: [
      { id: "r10", alias: "Pareja V.", rating: 5, comment: "El jacuzzi lo cambia todo. Experiencia de lujo total.", date: "2026-03-19" },
      { id: "r11", alias: "Usuario G.", rating: 5, comment: "Perfecto para un aniversario express. Mi pareja quedo encantada.", date: "2026-03-14" },
      { id: "r12", alias: "Pareja B.", rating: 5, comment: "Vale cada peso. El detalle del champagne es un toque increible.", date: "2026-03-07" },
    ],
  },
  {
    id: "space-005",
    title: "Cozy Studio - Coyoacan",
    type: "studio",
    area: "Coyoacan",
    distanceKm: 4.5,
    pricePer30m: 10,
    instantAccess: false,
    imageUrl: "https://images.unsplash.com/photo-1540518614846-7eded433c457?w=600&q=80",
    rating: 4.3,
    reviewCount: 67,
    description: "Estudio acogedor en zona residencial de Coyoacan. Ambiente tranquilo y privado, ideal para quienes buscan algo mas relajado y economico.",
    amenities: ["Wi-Fi", "Ventilador", "Cama Double", "Bano privado", "Lockbox"],
    reviews: [
      { id: "r13", alias: "Usuario P.", rating: 4, comment: "Buena opcion economica. Limpio y funcional.", date: "2026-03-17" },
      { id: "r14", alias: "Pareja N.", rating: 5, comment: "Nos encanto la tranquilidad de la zona. Muy privado.", date: "2026-03-11" },
      { id: "r15", alias: "Usuario T.", rating: 4, comment: "Simple pero cumple. Buen precio para la zona.", date: "2026-03-03" },
    ],
  },
  {
    id: "space-006",
    title: "Penthouse View - Santa Fe",
    type: "apartment-1br",
    area: "Santa Fe",
    distanceKm: 8.2,
    pricePer30m: 28,
    instantAccess: true,
    imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80",
    rating: 5.0,
    reviewCount: 42,
    description: "Penthouse exclusivo con vista panoramica a la ciudad. Decoracion de disenador, cama premium y amenidades de hotel 5 estrellas. La experiencia mas premium de SPACED.",
    amenities: ["Vista panoramica", "Jacuzzi", "Cama King", "Smart TV 65\"", "Mini bar", "Bano doble", "Cerradura digital", "Room service disponible"],
    reviews: [
      { id: "r16", alias: "Pareja E.", rating: 5, comment: "Sin palabras. La vista de noche es espectacular. Top experience.", date: "2026-03-21" },
      { id: "r17", alias: "Usuario W.", rating: 5, comment: "Esto es otro nivel. Si pueden pagarlo, haganlo.", date: "2026-03-13" },
      { id: "r18", alias: "Pareja C.", rating: 5, comment: "Celebramos nuestro aniversario aqui. Mejor que cualquier hotel.", date: "2026-03-06" },
    ],
  },
  {
    id: "space-007",
    title: "Neon Room - Centro",
    type: "private-room",
    area: "Centro Historico",
    distanceKm: 1.8,
    pricePer30m: 15,
    instantAccess: true,
    imageUrl: "https://images.unsplash.com/photo-1596178065887-1198b6148b2b?w=600&q=80",
    rating: 4.7,
    reviewCount: 198,
    description: "Habitacion tematica con iluminacion neon y decoracion moderna. Muy popular entre parejas jovenes. Musica ambiental y luces RGB controlables.",
    amenities: ["Luces RGB", "Bluetooth speaker", "Cama King", "Bano privado", "Cerradura digital", "Espejo de cuerpo completo"],
    reviews: [
      { id: "r19", alias: "Pareja Z.", rating: 5, comment: "Las luces neon le dan un vibe increible. Super cool.", date: "2026-03-22" },
      { id: "r20", alias: "Usuario H.", rating: 4, comment: "Muy instagrameable y comodo. El speaker bluetooth es un gran plus.", date: "2026-03-15" },
      { id: "r21", alias: "Pareja Y.", rating: 5, comment: "Nuestro lugar favorito. Ya hemos ido 3 veces.", date: "2026-03-09" },
    ],
  },
  {
    id: "space-008",
    title: "Garden Suite - Del Valle",
    type: "studio",
    area: "Del Valle",
    distanceKm: 2.8,
    pricePer30m: 16,
    instantAccess: true,
    imageUrl: "https://images.unsplash.com/photo-1545232979-8bf68ee9b1af?w=600&q=80",
    rating: 4.5,
    reviewCount: 93,
    description: "Estudio con jardin privado interior. Ambiente natural y relajante con plantas, fuente de agua y luz natural. Perfecto para desconectar.",
    amenities: ["Jardin privado", "Fuente de agua", "Cama Queen", "Bano privado", "Cerradura digital", "Te y cafe incluido"],
    reviews: [
      { id: "r22", alias: "Usuario Q.", rating: 5, comment: "El jardin es hermoso. Se siente como un oasis en la ciudad.", date: "2026-03-20" },
      { id: "r23", alias: "Pareja I.", rating: 4, comment: "Muy relajante. Ideal para desestresarse. El te incluido es un lindo detalle.", date: "2026-03-14" },
      { id: "r24", alias: "Usuario O.", rating: 5, comment: "Perfecto para una siesta o descanso express. Super tranquilo.", date: "2026-03-04" },
    ],
  },
];
